version: '3.7'

services:
  db:
    image: postgres:14.7-alpine
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data

  api:
    build: .
    entrypoint: ./asgi-entrypoint.sh
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
  
  redis:
    image: redis:alpine
    expose:
      - 6379
  
  celery:
    build: .
    working_dir: /app/src
    command: celery -A core worker -l info
    depends_on:
      - redis
      - api
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  db:
