version: '3.7'

services:
  db:
    image: postgres:14.7-alpine
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data

  api:
    build: .
    image: kermitlafrog61/devdynamos-api
    entrypoint: ./asgi-entrypoint.sh
    volumes:
      - .:/app
      - media:/app/media
    depends_on:
      - db
    env_file:
      - .env
    expose:
      - 8000

  redis:
    image: redis:alpine
    expose:
      - 6379

  celery:
    image: kermitlafrog61/devdynamos-api
    working_dir: /app/src
    command: celery -A core worker -l info
    depends_on:
      - redis
      - api
    env_file:
      - .env
    volumes:
      - .:/app

  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    env_file:
      - .env
    volumes:
      - media:/app/media
    depends_on:
      - api
    ports:
      - "80:80"

volumes:
  db:
  media:
