"""courses initial

Revision ID: 7f2fdd0e9925
Revises: 8ced472a0931
Create Date: 2023-07-25 14:48:31.305774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f2fdd0e9925'
down_revision = '8ced472a0931'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
