"""course owners and students

Revision ID: 805e958b1cd9
Revises: eb4d20502fa5
Create Date: 2023-07-26 13:20:51.735661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '805e958b1cd9'
down_revision = 'eb4d20502fa5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses_course_mentors',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses_course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_account.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'user_id')
    )
    op.create_table('courses_course_students',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses_course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_account.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courses_course_students')
    op.drop_table('courses_course_mentors')
    # ### end Alembic commands ###
