"""courses initial

Revision ID: aba3a47e390b
Revises: 7f2fdd0e9925
Create Date: 2023-07-25 14:51:18.983760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aba3a47e390b'
down_revision = '7f2fdd0e9925'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses_course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('about', sa.String(), nullable=False),
    sa.Column('profession_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['profession_id'], ['auth_profession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses_lection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('about', sa.String(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('video_link', sa.String(), nullable=True),
    sa.Column('homework_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses_course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courses_lection')
    op.drop_table('courses_course')
    # ### end Alembic commands ###
