"""account avatar

Revision ID: eb4d20502fa5
Revises: aba3a47e390b
Create Date: 2023-07-26 09:07:35.379403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb4d20502fa5'
down_revision = 'aba3a47e390b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_account', sa.Column('avatar_url', sa.String(), nullable=True))
    op.alter_column('auth_account', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('auth_account', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth_account', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('auth_account', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('auth_account', 'avatar_url')
    # ### end Alembic commands ###
